[package]
name = "slim"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.107"
reqwest = { version = "0.11.20", features = ["blocking", "json"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
